### ISSUE TITLE
Replace original parcom repo with your fork

### ISSUE THREAD

**Issue by ghost** [jonsterling/sml-parcom-wrapper#2]
Original repo's author is not accepting pull requests now. What about replacing parcom with your's fork?

**Comment by jonsterling** [comment]
Hmm, that might be a good point. We may end up being the biggest user of parcom, so it may be desirable for us to be the primary maintainers of whatever we use.

**Comment by jonsterling** [comment]
@ak3n I've created a fork here: https://github.com/RedPRL/sml-parcom. I'm in the process of migrating our libraries to depend on it now.

**Comment by jonsterling** [comment]
@ak3n I noticed you had a PR open on the main repository; feel free to re-open it against `RedPRL/sml-parcom`, and we'll get it merged in.
